eureka:
  instance:
    hostname: localhost
client:
  service-url:
    defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: students
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/students?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8090
